Async grpc upsert
pinecone-io/pinecone-python-client pull request #14
Opened 2021-11-25 01:08 UTC by rajat08

2021-11-25 06:24 UTC, mutayroei commented
[ch10321]

2021-11-29 07:54 UTC, mutayroei commented on pinecone/core/grpc/index_grpc.py
> +    def __init__(self, name: str, channel=None, grpc_config: GRPCClientConfig = None, _endpoint_override: str = None,
@rajat08  I believe that for the default index the parameter is called index_name

2021-11-29 08:08 UTC, mutayroei commented
@benjaminran  can you review?

2021-12-01 14:04 UTC, rajat08 commented
@mutayroei @benjaminran 
Since all the info form the grpc error is condensed in the debug string, we can pass this to PineconeException and get a 'nicer sounding' error. However _InactiveRPCError would be visible in the trace. Would the ideal behavior be to raise PineconeError at an earlier step?

2021-12-05 09:24 UTC, benjaminran requested changes
Posted a couple comments about the async logic.

The error handling logic looks good! I think it's a good thing to include the _InactiveRpcError deeper inside the trace.

2021-12-11 16:38 UTC, mutayroei approved these changes

2021-12-12 07:20 UTC, merged